export const PLANT_IMAGE_MAP = {
  "Money Plant":"https://source.unsplash.com/featured/?pothos,devil%27s-ivy,houseplant",
  "Snake Plant":"https://source.unsplash.com/featured/?snake-plant,sansevieria,houseplant",
  "Spider Plant":"https://source.unsplash.com/featured/?spider-plant,chlorophytum,houseplant",
  "Peace Lily":"https://source.unsplash.com/featured/?peace-lily,spathiphyllum,houseplant,white-flower",
  "Areca Palm":"https://source.unsplash.com/featured/?areca-palm,dypsis,houseplant",
  "Boston Fern":"https://source.unsplash.com/featured/?boston-fern,nephrolepis,fern",
  "Aloe Vera":"https://source.unsplash.com/featured/?aloe-vera,aloe,succulent",
  "Jade Plant":"https://source.unsplash.com/featured/?jade-plant,crassula,succulent",
  "ZZ Plant":"https://source.unsplash.com/featured/?zz-plant,zamioculcas,houseplant",
  "Rubber Plant":"https://source.unsplash.com/featured/?rubber-plant,ficus-elastica,houseplant",
  "Fiddle Leaf Fig":"https://source.unsplash.com/featured/?fiddle-leaf-fig,ficus-lyrata,houseplant",
  "Pothos Golden":"https://source.unsplash.com/featured/?golden-pothos,epipremnum-aureum,houseplant",
  "Chinese Evergreen":"https://source.unsplash.com/featured/?chinese-evergreen,aglaonema,houseplant",
  "English Ivy":"https://source.unsplash.com/featured/?english-ivy,hedera-helix,ivy",
  "Lavender":"https://source.unsplash.com/featured/?lavender,lavandula,flower",
  "Basil":"https://source.unsplash.com/featured/?basil,ocimum,herb",
  "Rosemary":"https://source.unsplash.com/featured/?rosemary,rosmarinus,herb",
  "Mint":"https://source.unsplash.com/featured/?mint,mentha,herb",
  "Thyme":"https://source.unsplash.com/featured/?thyme,thymus,herb",
  "Chrysanthemum":"https://source.unsplash.com/featured/?chrysanthemum,flower",
  "Bougainvillea":"https://source.unsplash.com/featured/?bougainvillea,flower",
  "Hibiscus":"https://source.unsplash.com/featured/?hibiscus,flower",
  "Jasmine":"https://source.unsplash.com/featured/?jasmine,flower",
  "Marigold":"https://source.unsplash.com/featured/?marigold,tagetes,flower",
  "Geranium":"https://source.unsplash.com/featured/?geranium,pelargonium,flower",
  "Cactus Bunny Ear":"https://source.unsplash.com/featured/?bunny-ear-cactus,opuntia,succulent",
  "Echeveria":"https://source.unsplash.com/featured/?echeveria,rosette,succulent",
  "Haworthia":"https://source.unsplash.com/featured/?haworthia,succulent",
  "Sedum Burrito":"https://source.unsplash.com/featured/?burro%27s-tail,sedum,morganianum,succulent",
  "Kalanchoe":"https://source.unsplash.com/featured/?kalanchoe,flower,succulent",
  "Dracaena":"https://source.unsplash.com/featured/?dracaena,houseplant",
  "Croton":"https://source.unsplash.com/featured/?croton,codiaeum,houseplant",
  "Calathea":"https://source.unsplash.com/featured/?calathea,prayer-plant,houseplant",
  "Dieffenbachia":"https://source.unsplash.com/featured/?dieffenbachia,dumb-cane,houseplant",
  "Philodendron":"https://source.unsplash.com/featured/?philodendron,houseplant",
  "Monstera Deliciosa":"https://source.unsplash.com/featured/?monstera-deliciosa,monstera,houseplant",
  "Syngonium":"https://source.unsplash.com/featured/?syngonium,arrowhead,houseplant",
  "Areca Bambino":"https://source.unsplash.com/featured/?areca-palm,bambino,houseplant",
  "Rubber Variegata":"https://source.unsplash.com/featured/?variegated-rubber-plant,ficus-elastica,houseplant",
  "Aglaonema Red":"https://source.unsplash.com/featured/?aglaonema,red-aglaonema,houseplant",
  "Lucky Bamboo":"https://source.unsplash.com/featured/?lucky-bamboo,dracaena-sanderiana",
  "Bird of Paradise":"https://source.unsplash.com/featured/?bird-of-paradise,strelitzia,houseplant",
  "Fern Asparagus":"https://source.unsplash.com/featured/?asparagus-fern,houseplant",
  "Peperomia":"https://source.unsplash.com/featured/?peperomia,houseplant",
  "Schefflera":"https://source.unsplash.com/featured/?schefflera,umbrella-plant,houseplant",
  "Ixora":"https://source.unsplash.com/featured/?ixora,flower",
  "Coleus":"https://source.unsplash.com/featured/?coleus,painted-nettle,plant",
  "Areca Golden":"https://source.unsplash.com/featured/?golden-areca-palm,dypsis",
  "Chlorophytum Lemon":"https://source.unsplash.com/featured/?chlorophytum,lemon,spider-plant"
}